version: '3.9'

networks:
  monitoring:

volumes:
  prometheus-data:
  grafana-data:

services:
  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    expose:
      - 9090
    networks:
      - monitoring

  nordea-rate-metrics:
    image: kerwood/nordea-rate-metrics
    container_name: nordea-rate-metrics
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:8.5.0
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - monitoring