version: '3.9'

networks:
  nordea-net:
  traefik-proxy:
    external: true

volumes:
  prometheus-data:
  grafana-data:

services:
  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: nordea-prometheus
    restart: unless-stopped
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=1y'
    expose:
      - 9090
    networks:
      - nordea-net

  nordea-rate-metrics:
    image: kerwood/nordea-rate-metrics
    container_name: nordea-rate-metrics
    restart: unless-stopped
    environment:
      ROCKET_ADDRESS: 0.0.0.0
    expose:
      - 8000
    networks:
      - nordea-net

  grafana:
    image: grafana/grafana:8.5.0
    container_name: nordea-grafana
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
      - ./configs/grafana-datasource.yml:/etc/grafana/provisioning/datasources/grafana-datasource.yml
      - ./configs/grafana-dashboard.yml:/etc/grafana/provisioning/dashboards/grafana-dashboard.yml
      - ./configs/nordea-rate-metrics.json:/var/lib/grafana/dashboards/nordea-rate-metrics.json
    expose:
      - 3000
    networks:
      - traefik-proxy
      - nordea-net
    labels:
      - traefik.enable=true
      - traefik.http.services.nordea-kredit-rate.loadbalancer.server.port=3000
      - traefik.http.routers.nordea-kredit-rate.rule=Host(`nordea.example.com`)
      - traefik.http.routers.nordea-kredit-rate.tls.certresolver=le
      - traefik.http.routers.nordea-kredit-rate.entrypoints=websecure
      - traefik.docker.network=traefik-proxy