{
 "title": "Nordea Kredit Fast Rente",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Løbetid: 30 , Afdragsfri: 0",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nordea_kredit{repayment_freedom_max=\"0\", loan_period_max=\"30\", fund_name!=\"\"}",
     "legendFormat": "{{fund_name}}"
    }
   ]
  },
  {
   "title": "Løbetid: 30 , Afdragsfri: 10",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "nordea_kredit{repayment_freedom_max=\"10\", loan_period_max=\"30\", fund_name!=\"\"}",
     "legendFormat": "{{fund_name}}"
    }
   ]
  },
  {
   "title": "Løbetid: 30 , Afdragsfri: 30",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "nordea_kredit{repayment_freedom_max=\"30\", loan_period_max=\"30\", fund_name!=\"\"}",
     "legendFormat": "{{fund_name}}"
    }
   ]
  },
  {
   "title": "Løbetid: 20 , Afdragsfri: 0",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "nordea_kredit{repayment_freedom_max=\"0\", loan_period_max=\"20\", fund_name!=\"\"}",
     "legendFormat": "{{fund_name}}"
    }
   ]
  },
  {
   "title": "Løbetid: 10/15 , Afdragsfri: 0",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "nordea_kredit{repayment_freedom_max=\"0\", loan_period_max=\"15\"} or nordea_kredit{repayment_freedom_max=\"0\", loan_period_max=\"10\", fund_name!=\"\"}",
     "legendFormat": "{{fund_name}} [{{loan_period_max}}]"
    }
   ]
  }
 ]
}